Update library
amperka/Multiservo pull request #2
Opened 2021-04-28 11:41 UTC by igor605ds

I fixed and update library, important changes:

1. Added API_ru.md
1. Fixed the framework of the files according to Arduino Library Specification.
2. Added support for I²C-bus selection.
3. Replaced define with constexpr.
4. Added methods read voltage and current. Added example.
5. Added firmware files for v1 and v2

2021-04-28 13:21 UTC, S-VIN reviewed
Я несколько замечаний по архетиктуре добавил. Замечания некритичные.

2021-04-28 13:21 UTC, S-VIN commented on src/Multiservo.cpp
> +void Multiservo::attach(int pin, int minPulse, int maxPulse) {
Лучше сделать эту функцию через перегрузку, а не через значение по умолчанию, чтобы нельзя было вызвать её с двумя параметрами.
Как здесь: https://github.com/arduino-libraries/Servo/blob/master/src/avr/Servo.cpp

2021-04-28 13:21 UTC, S-VIN commented on src/Multiservo.cpp
> +bool Multiservo::readVoltageCurrent() {
А почему метод не приватный? Лучше сделать его приватным и запускать в getVoltage, getCurrent. Зачем он возвращает буль? Он же фолз никогда не вернет.

2021-04-28 13:21 UTC, S-VIN commented on src/Multiservo.h
> +class Multiservo {
Я бы отнаследовался от оригинального Servo и переопределил бы все его методы. Так будет гарантия, что сигнатуры методов совпадают.

2021-04-28 13:36 UTC, tolikivanov commented
LGTM

2021-04-28 13:37 UTC, tolikivanov approved these changes
LGTM

2021-04-28 13:48 UTC, igor605ds reviewed
Ответил на коменты, внесу изменения в следующем комите.

2021-04-28 13:48 UTC, igor605ds commented on src/Multiservo.cpp
> +void Multiservo::attach(int pin, int minPulse, int maxPulse) {
Ок, тут убедил.

2021-04-28 13:48 UTC, igor605ds commented on src/Multiservo.cpp
> +bool Multiservo::readVoltageCurrent() {
Метод не приватный, потому что пользователь явно вызывает его, для считывания данных. А затем получает значения через get. Это у нас всегда такая структура в подобных случаях. Насчет bool, думаю добавлю ситуацию когда будет false.

2021-04-28 13:48 UTC, igor605ds commented on src/Multiservo.h
> +class Multiservo {
Я думаю это уже слишком сложно, т.к.текущая версия либы и так правит куча старых косяков. Я попробую, но не обещаю.

2021-04-29 08:07 UTC, S-VIN commented on src/Multiservo.cpp
> +bool Multiservo::readVoltageCurrent() {
Я с этим не согласен. Получать данные черег геттер - логично, а вызывать перед запросом непонятную функцию - сюр какой-то. Новичкам будет не очевидно, что она делает. Если есть функция обновляющая данные, то она должна быть внутренней, либо должна быть обусловлена логикой работы программы (если обновление медленное и обновляет сразу всё). 
Тут же второй случай не подходит, значит нужно первым делать.

2021-04-29 08:07 UTC, S-VIN commented on src/Multiservo.h
> +class Multiservo {
У тебя всё готово почти итак.

2021-04-29 08:24 UTC, nkrkv commented on src/Multiservo.cpp
> +bool Multiservo::readVoltageCurrent() {
> Я с этим не согласен. Получать данные черег геттер - логично, а вызывать перед запросом непонятную функцию - сюр какой-то. Новичкам будет не очевидно, что она делает.

Не согласен с несогласием. Паттерн read/get придумали не мы, он повсеместен в разных комьюнити-библиотеках. Мы его приняли на вооружение и также используем повсеместно. Консистентность в данном случае превыше всего.

2021-04-29 08:30 UTC, nkrkv commented on API_ru.md
> +### `uint16_t getVoltage()`
```suggestion
### `uint16_t getVoltage() const`
```

2021-04-29 08:30 UTC, nkrkv commented on API_ru.md
> +### `uint16_t getCurrent()`
```suggestion
### `uint16_t getCurrent() const`
```

2021-04-29 08:30 UTC, nkrkv commented on API_ru.md
> +### `bool attached()`
```suggestion
### `bool attached() const`
```

2021-04-29 08:30 UTC, nkrkv commented on API_ru.md
> +### `int read()`
```suggestion
### `int getAngleDegrees() const`
```

2021-04-29 08:30 UTC, nkrkv commented on API_ru.md
> +### `int readMicroseconds()`
```suggestion
### `int getMicroseconds() const`
```

2021-04-29 08:30 UTC, nkrkv commented on src/Multiservo.h
> +class Multiservo {
Negative. Если унаследоваться, будут иллюзии на тему того, что можно хранить поинтер на суперкласс (т.е. `Servo*`), вызывать методы через него и получать корректное поведение. А это не так: насколько я помню, методы `Servo` не `virtual`, а следовательно не предназначены для перекрытия.

Суммарно: унаследовавшись от `Servo` мы разрешим компилятору пропускать `Multiservo*` туда, где ожидается `Servo*` без ошибки времени компиляции. Но фактически серво работать не будет. Т.е. будет ошибка поведения. А это сильно хуже честной ошибки времени компиляции.

Считаю, что наследоваться деструктивно и не нужно.

2021-04-29 08:31 UTC, nkrkv requested changes
`const`, забываем `const` в методах постоянно

2021-04-29 08:45 UTC, igor605ds commented
@nkrkv Согласен про `const`. Самое смешное, что помнил про него, но не  во всех методах поставил. Исправим.

2021-04-30 11:45 UTC, igor605ds reviewed
Принял правки.

@nkrkv Есть пара возражений по двум замечаниям в переименовании методов, подробности ниже.

2021-04-30 11:45 UTC, igor605ds commented on API_ru.md
> +### `int read()`
С `const` согласен. В h. файле так и было. А вот в API забыл указать. Done.

А вот с переименование, попытаюсь поспорить:
1. Этот метод уже был в прошлой версии либы, думаю его не стоить переименовывать.
2. Все имена методов, хотел оставить одинаковые с методами либы Servo:
https://www.arduino.cc/reference/en/libraries/servo/
https://github.com/arduino-libraries/Servo/blob/master/src/Servo.h

2021-04-30 11:45 UTC, igor605ds commented on API_ru.md
> +### `int readMicroseconds()`
Аналогично с методом выше.

2021-04-30 11:45 UTC, igor605ds commented on API_ru.md
> +### `bool attached()`
Done

2021-04-30 11:45 UTC, igor605ds commented on API_ru.md
> +### `uint16_t getVoltage()`
Done

2021-04-30 11:45 UTC, igor605ds commented on API_ru.md
> +### `uint16_t getCurrent()`
Done

2021-04-30 11:45 UTC, igor605ds commented on src/Multiservo.cpp
> +void Multiservo::attach(int pin, int minPulse, int maxPulse) {
Done

2021-04-30 12:18 UTC, nkrkv approved these changes
:+1:

2021-04-30 12:36 UTC, S-VIN approved these changes
👌

2021-04-30 12:41 UTC, igor605ds commented
🎉 🎉 🎉

2021-04-30 12:41 UTC, merged